/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_oauth.h"

authorization_token_t *
request_authorization_1_svc(char *argp, struct svc_req *rqstp)
{
	static authorization_token_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

access_token_t *
request_access_token_1_svc(client_status_t *argp, struct svc_req *rqstp)
{
	static access_token_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
validate_delegated_action_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

approve_request_token_t *
approve_request_token_1_svc(void *argp, struct svc_req *rqstp)
{
	static approve_request_token_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
