/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_oauth.h"

bool_t
xdr_status_t (XDR *xdrs, status_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_authorization_token_t (XDR *xdrs, authorization_token_t *objp)
{
	register int32_t *buf;

	 if (!xdr_status_t (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token, 15))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_t (XDR *xdrs, access_token_t *objp)
{
	register int32_t *buf;

	 if (!xdr_status_t (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token, 15))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->reset_token, 15))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client_access_t (XDR *xdrs, client_access_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, 15))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->authorization_token, 15))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->reset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_action_request_t (XDR *xdrs, action_request_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->instruction, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, 15))
		 return FALSE;
	return TRUE;
}
