/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_oauth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "utils.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int token_timeout;
char *client_file;
char *resources_file;
char *approvals_file;

char **user_ids;
char **resources;
struct approvals_t **approvals;

int token_rights_size;
struct token_rights_t **token_rights;

int users_no;
int resources_no;
int approvals_no;

int status_size;
struct client_access_t **statuses;

/*
 * the list of authorization tokens and their
 * correspondent access tokens;
 */
user_access_token **token_pairs;
int token_pairs_size;

/* index used  */
int approvals_index;

static void
rpc_oauth_program_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *request_authorization_1_arg;
		client_access_t request_access_token_1_arg;
		action_request_t validate_delegated_action_1_arg;
		char *approve_request_token_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQUEST_AUTHORIZATION:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_authorization_token_t;
		local = (char *(*)(char *, struct svc_req *)) request_authorization_1_svc;
		break;

	case REQUEST_ACCESS_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_client_access_t;
		_xdr_result = (xdrproc_t) xdr_access_token_t;
		local = (char *(*)(char *, struct svc_req *)) request_access_token_1_svc;
		break;

	case VALIDATE_DELEGATED_ACTION:
		_xdr_argument = (xdrproc_t) xdr_action_request_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) validate_delegated_action_1_svc;
		break;

	case APPROVE_REQUEST_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) approve_request_token_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPC_OAUTH_PROGRAM, RPC_OAUTH_VERS);

	client_file = argv[1];
	resources_file = argv[2];
	approvals_file = argv[3];
	token_timeout = atoi(argv[4]);

	read_files();

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_OAUTH_PROGRAM, RPC_OAUTH_VERS, rpc_oauth_program_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPC_OAUTH_PROGRAM, RPC_OAUTH_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_OAUTH_PROGRAM, RPC_OAUTH_VERS, rpc_oauth_program_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPC_OAUTH_PROGRAM, RPC_OAUTH_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
