services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    ports:
      - '1883:1883'
    networks:
      - adapter

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - database
      - dashboard

  grafana:
    image: grafana/grafana:latest
    ports:
      - '80:80'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - dashboard

  adapter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adapter
    restart: always
    depends_on:
      - mosquitto
    networks:
      - adapter
      - database

volumes:
  influxdb-storage: {}
  grafana-storage: {}

networks:
  adapter: {}
  database: {}
  dashboard: {}