version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
    networks:
      - adapter

  influxdb:
    image: influxdb:1.5
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=database_influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - database
      - dashboard

  grafana:
    image: grafana/grafana:latest
    ports:
      - '80:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2021
    networks:
      - dashboard

  adapter:
    image: adapter
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - adapter
      - database

volumes:
  influxdb-storage: {}
  grafana-storage: {}

networks:
  adapter: {}
  database: {}
  dashboard: {}
